### ISSUE TITLE
How to use with Laravel Mix

### ISSUE THREAD

**Issue by solamichealolawale** [schneidmaster/sitemap-webpack-plugin#49]
I have some few questions about how to use it with Laravel mix
- Will it work with laravel mix since it's more like a wrapper for webpack on laravel project (Which I doubt, since the URL are defined in the web.php file and not Vue router)
- What are the possibilites of getting it to work with Laravel + Vuejs apps
- If yes, how will it be configured since I can't get it to work locally here

**Comment by schneidmaster** [comment]
Hi! The plugin should work just fine with Laravel Mix using their [custom webpack config](https://laravel.com/docs/8.x/mix#custom-webpack-configuration). However it wouldn't be very ergonomic since Laravel is a server side framework and the routes are defined on the server, so you'd probably have to maintain a duplicate list of routes in the plugin config. I'm not very familiar with Laravel but you might have an easier time with a server side plugin like [this](https://github.com/spatie/laravel-sitemap).
